version: 2

build:
  os: ubuntu-22.04
  image: "latest"
  tools:
    python: "3.9"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: "pip"
      path: "."  # This installs the package from the current directory where setup.py is located.
