# .readthedocs.yaml

# Basic configuration for Read the Docs
version: 2

# Build tools and settings
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"  # Specify Python version

# Python dependencies
python:
  install:
    - method: pip
      path: .  # Install your package in the Read the Docs environment
